INSERT INTO departments (name)
VALUES
    ('Receiving'),
    ('Inventory'),
    ('Sales'),
    ('Management'),
    ('Human Resources'),
    ('Customer Service'),
    ('Security');

INSERT INTO roles (title, salary, department_id)
VALUES
    ('Sales Associate', 23712.00, 3),
    ('Cashier', 24356.80, 3),
    ('Inventory Associate', 27996.80, 1),
    ('Customer Service Rep', 28558.40, 6),
    ('Warehouse Clerk', 29140.80, 1),
    ('Assistant Store Manager', 28285.00, 4),
    ('Inventory Control Specialist', 31969.60, 7),
    ('Floor Manager', 36928.00, 4),
    ('Department Manager', 49604.00, 4),
    ('Employee Services', 25683.00, 5);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES
    ('Carla','Singer', 4, 10),
    ('Lila','Borwan', 8, 3),
    ('Charles','Trafler', 9, null),
    ('Sara','Tortellar', 10, 3),
    ('Samuel', 'Johnson', 5, 3),
    ('John', 'Dryden', 6, 38),
    ('Alexander', 'Pope', 3, 10),
    ('Lionel', 'Johnson', 6, 38),
    ('Aubrey', 'Beardsley', 1, 2),
    ('Tulse', 'Luper', 8, 3),
    ('William', 'Morris', 4, 10),
    ('George', 'Shaw', 8, 3),
    ('Arnold', 'Bennett', 2, 2),
    ('Algernon', 'Blackwood', 2, 2),
    ('Rhoda', 'Broughton', 2, 2),
    ('Hart', 'Crane', 1, 2),
    ('Vitorio', 'DeSica', 1, 2),
    ('Wilkie', 'Collins', 1, 2),
    ('Elizabeth', 'Gaskell', 4, 10),
    ('George', 'Sand', 8, 3),
    ('Vernon', 'Lee', 4, 10),
    ('Arthur', 'Machen', 3, 10),
    ('Frederick', 'Marryat', 6, 38),
    ('Harriet', 'Martineau', 2, 2),
    ('George', 'Meredith', 2, 2),
    ('Margaret', 'Oliphant', 2, 2),
    ('Anthony', 'Trollope', 1, 2),
    ('Charlotte', 'Yonge', 10, 3),
    ('Horace', 'Walpole', 7, 38),
    ('Matthew', 'Lewis', 5, 3),
    ('William', 'Bedford', 7, 38),
    ('Anne', 'Radcliffe', 1, 2),
    ('Charles', 'Brown', 2, 2),
    ('Eliza', 'Parsons', 2, 2),
    ('Susan', 'Hill', 4, 10),
    ('Sydney', 'Owenson', 2, 2),
    ('Hubert', 'Crackanthorpe', 8, 3),
    ('William', 'Carleton', 9, null),
    ('Gerald', 'Griffin', 3, 10);